// AUTO-GENERATED by .ds-sync/gen-preview-data.mjs from src/demo/demoData.js.
// Static, pre-computed props for the design-sync preview cards — no scoring
// import (so the toxic-regex module never enters the preview bundle) and no
// live computation. Regenerate if the demo fixture changes.
export const tournament = {
  "id": "demo",
  "name": "2026 US Open Pick 'em",
  "pga_name": "U.S. Open",
  "course_name": "Shinnecock Hills",
  "status": "open",
  "pick_count": 8,
  "scores_to_keep": 5,
  "lock_time": null,
  "stake_amount": 25,
  "payout_structure": [
    60,
    30,
    10
  ]
};
export const tiers = [
  {
    "id": "demo-tier-1",
    "tier_number": 1,
    "label": "Tier 1",
    "tier_players": [
      {
        "id": "tp-1-46046",
        "player_id": "46046",
        "player_name": "Scottie Scheffler",
        "odds": 550
      },
      {
        "id": "tp-1-28237",
        "player_id": "28237",
        "player_name": "Rory McIlroy",
        "odds": 1200
      },
      {
        "id": "tp-1-46970",
        "player_id": "46970",
        "player_name": "Jon Rahm",
        "odds": 1400
      },
      {
        "id": "tp-1-48081",
        "player_id": "48081",
        "player_name": "Xander Schauffele",
        "odds": 1800
      },
      {
        "id": "tp-1-57366",
        "player_id": "57366",
        "player_name": "Cameron Young",
        "odds": 2000
      },
      {
        "id": "tp-1-30911",
        "player_id": "30911",
        "player_name": "Tommy Fleetwood",
        "odds": 2000
      }
    ]
  },
  {
    "id": "demo-tier-2",
    "tier_number": 2,
    "label": "Tier 2",
    "tier_players": [
      {
        "id": "tp-2-52955",
        "player_id": "52955",
        "player_name": "Ludvig Åberg",
        "odds": 2200
      },
      {
        "id": "tp-2-34363",
        "player_id": "34363",
        "player_name": "Tyrrell Hatton",
        "odds": 3300
      },
      {
        "id": "tp-2-47959",
        "player_id": "47959",
        "player_name": "Bryson DeChambeau",
        "odds": 3300
      },
      {
        "id": "tp-2-37455",
        "player_id": "37455",
        "player_name": "Si Woo Kim",
        "odds": 3500
      },
      {
        "id": "tp-2-59095",
        "player_id": "59095",
        "player_name": "Chris Gotterup",
        "odds": null
      },
      {
        "id": "tp-2-40098",
        "player_id": "40098",
        "player_name": "Matt Fitzpatrick",
        "odds": null
      }
    ]
  },
  {
    "id": "demo-tier-3",
    "tier_number": 3,
    "label": "Tier 3",
    "tier_players": [
      {
        "id": "tp-3-34098",
        "player_id": "34098",
        "player_name": "Russell Henley",
        "odds": 3500
      },
      {
        "id": "tp-3-36689",
        "player_id": "36689",
        "player_name": "Brooks Koepka",
        "odds": 4000
      },
      {
        "id": "tp-3-47504",
        "player_id": "47504",
        "player_name": "Sam Burns",
        "odds": 4000
      },
      {
        "id": "tp-3-34360",
        "player_id": "34360",
        "player_name": "Patrick Reed",
        "odds": 4000
      },
      {
        "id": "tp-3-50525",
        "player_id": "50525",
        "player_name": "Collin Morikawa",
        "odds": 4000
      },
      {
        "id": "tp-3-52453",
        "player_id": "52453",
        "player_name": "Nicolai Højgaard",
        "odds": null
      }
    ]
  },
  {
    "id": "demo-tier-4",
    "tier_number": 4,
    "label": "Tier 4",
    "tier_players": [
      {
        "id": "tp-4-51766",
        "player_id": "51766",
        "player_name": "Wyndham Clark",
        "odds": 4000
      },
      {
        "id": "tp-4-46717",
        "player_id": "46717",
        "player_name": "Viktor Hovland",
        "odds": 4500
      },
      {
        "id": "tp-4-33448",
        "player_id": "33448",
        "player_name": "Justin Thomas",
        "odds": 4500
      },
      {
        "id": "tp-4-35450",
        "player_id": "35450",
        "player_name": "Patrick Cantlay",
        "odds": 4500
      },
      {
        "id": "tp-4-22405",
        "player_id": "22405",
        "player_name": "Justin Rose",
        "odds": 4500
      },
      {
        "id": "tp-4-39324",
        "player_id": "39324",
        "player_name": "J.J. Spaun",
        "odds": 5000
      }
    ]
  },
  {
    "id": "demo-tier-5",
    "tier_number": 5,
    "label": "Tier 5",
    "tier_players": [
      {
        "id": "tp-5-48117",
        "player_id": "48117",
        "player_name": "Kurt Kitayama",
        "odds": 6600
      },
      {
        "id": "tp-5-46442",
        "player_id": "46442",
        "player_name": "Maverick McNealy",
        "odds": 6600
      },
      {
        "id": "tp-5-54591",
        "player_id": "54591",
        "player_name": "Ben Griffin",
        "odds": 6600
      },
      {
        "id": "tp-5-32839",
        "player_id": "32839",
        "player_name": "Hideki Matsuyama",
        "odds": 6600
      },
      {
        "id": "tp-5-45486",
        "player_id": "45486",
        "player_name": "Joaquin Niemann",
        "odds": 6600
      },
      {
        "id": "tp-5-27349",
        "player_id": "27349",
        "player_name": "Alex Noren",
        "odds": null
      }
    ]
  },
  {
    "id": "demo-tier-6",
    "tier_number": 6,
    "label": "Tier 6",
    "tier_players": [
      {
        "id": "tp-6-33204",
        "player_id": "33204",
        "player_name": "Shane Lowry",
        "odds": 6600
      },
      {
        "id": "tp-6-52215",
        "player_id": "52215",
        "player_name": "Robert MacIntyre",
        "odds": 6600
      },
      {
        "id": "tp-6-37378",
        "player_id": "37378",
        "player_name": "Min Woo Lee",
        "odds": 6600
      },
      {
        "id": "tp-6-34046",
        "player_id": "34046",
        "player_name": "Jordan Spieth",
        "odds": 6600
      },
      {
        "id": "tp-6-34099",
        "player_id": "34099",
        "player_name": "Harris English",
        "odds": 8000
      },
      {
        "id": "tp-6-46414",
        "player_id": "46414",
        "player_name": "Aaron Rai",
        "odds": 8000
      }
    ]
  },
  {
    "id": "demo-tier-7",
    "tier_number": 7,
    "label": "Wildcard 1",
    "tier_players": [
      {
        "id": "tp-7-35891",
        "player_id": "35891",
        "player_name": "Cameron Smith",
        "odds": 9000
      },
      {
        "id": "tp-7-49855",
        "player_id": "49855",
        "player_name": "Kristoffer Reitan",
        "odds": 9000
      },
      {
        "id": "tp-7-24502",
        "player_id": "24502",
        "player_name": "Adam Scott",
        "odds": 9000
      },
      {
        "id": "tp-7-34021",
        "player_id": "34021",
        "player_name": "Bud Cauley",
        "odds": 9000
      },
      {
        "id": "tp-7-59018",
        "player_id": "59018",
        "player_name": "Ryan Gerard",
        "odds": 9000
      },
      {
        "id": "tp-7-55721",
        "player_id": "55721",
        "player_name": "Alex Fitzpatrick",
        "odds": 10000
      }
    ]
  },
  {
    "id": "demo-tier-8",
    "tier_number": 8,
    "label": "Wildcard 2",
    "tier_players": [
      {
        "id": "tp-8-60386",
        "player_id": "60386",
        "player_name": "Sudarshan Yellamaraju",
        "odds": 20000
      },
      {
        "id": "tp-8-58168",
        "player_id": "58168",
        "player_name": "Davis Thompson",
        "odds": 20000
      },
      {
        "id": "tp-8-51977",
        "player_id": "51977",
        "player_name": "Max Greyserman",
        "odds": 20000
      },
      {
        "id": "tp-8-39975",
        "player_id": "39975",
        "player_name": "Michael Kim",
        "odds": 22500
      },
      {
        "id": "tp-8-51287",
        "player_id": "51287",
        "player_name": "Ryo Hisatsune",
        "odds": 22500
      },
      {
        "id": "tp-8-59141",
        "player_id": "59141",
        "player_name": "Matt McCarty",
        "odds": 25000
      }
    ]
  }
];
export const picks = [
  {
    "user_id": "demo-user-1",
    "player_id": "48081",
    "player_name": "Xander Schauffele",
    "status": "confirmed",
    "profiles": {
      "display_name": "Marcus Bennett"
    },
    "tiers": {
      "tier_number": 1,
      "label": "Tier 1"
    }
  },
  {
    "user_id": "demo-user-1",
    "player_id": "52955",
    "player_name": "Ludvig Åberg",
    "status": "confirmed",
    "profiles": {
      "display_name": "Marcus Bennett"
    },
    "tiers": {
      "tier_number": 2,
      "label": "Tier 2"
    }
  },
  {
    "user_id": "demo-user-1",
    "player_id": "47504",
    "player_name": "Sam Burns",
    "status": "confirmed",
    "profiles": {
      "display_name": "Marcus Bennett"
    },
    "tiers": {
      "tier_number": 3,
      "label": "Tier 3"
    }
  },
  {
    "user_id": "demo-user-1",
    "player_id": "33448",
    "player_name": "Justin Thomas",
    "status": "confirmed",
    "profiles": {
      "display_name": "Marcus Bennett"
    },
    "tiers": {
      "tier_number": 4,
      "label": "Tier 4"
    }
  },
  {
    "user_id": "demo-user-1",
    "player_id": "32839",
    "player_name": "Hideki Matsuyama",
    "status": "confirmed",
    "profiles": {
      "display_name": "Marcus Bennett"
    },
    "tiers": {
      "tier_number": 5,
      "label": "Tier 5"
    }
  },
  {
    "user_id": "demo-user-1",
    "player_id": "34099",
    "player_name": "Harris English",
    "status": "confirmed",
    "profiles": {
      "display_name": "Marcus Bennett"
    },
    "tiers": {
      "tier_number": 6,
      "label": "Tier 6"
    }
  },
  {
    "user_id": "demo-user-1",
    "player_id": "33141",
    "player_name": "Keegan Bradley",
    "status": "confirmed",
    "profiles": {
      "display_name": "Marcus Bennett"
    },
    "tiers": {
      "tier_number": 7,
      "label": "Wildcard 1"
    }
  },
  {
    "user_id": "demo-user-1",
    "player_id": "29484",
    "player_name": "Peter Uihlein",
    "status": "confirmed",
    "profiles": {
      "display_name": "Marcus Bennett"
    },
    "tiers": {
      "tier_number": 8,
      "label": "Wildcard 2"
    }
  },
  {
    "user_id": "demo-user-2",
    "player_id": "48081",
    "player_name": "Xander Schauffele",
    "status": "confirmed",
    "profiles": {
      "display_name": "Diane Cho"
    },
    "tiers": {
      "tier_number": 1,
      "label": "Tier 1"
    }
  },
  {
    "user_id": "demo-user-2",
    "player_id": "37455",
    "player_name": "Si Woo Kim",
    "status": "confirmed",
    "profiles": {
      "display_name": "Diane Cho"
    },
    "tiers": {
      "tier_number": 2,
      "label": "Tier 2"
    }
  },
  {
    "user_id": "demo-user-2",
    "player_id": "36689",
    "player_name": "Brooks Koepka",
    "status": "confirmed",
    "profiles": {
      "display_name": "Diane Cho"
    },
    "tiers": {
      "tier_number": 3,
      "label": "Tier 3"
    }
  },
  {
    "user_id": "demo-user-2",
    "player_id": "51766",
    "player_name": "Wyndham Clark",
    "status": "confirmed",
    "profiles": {
      "display_name": "Diane Cho"
    },
    "tiers": {
      "tier_number": 4,
      "label": "Tier 4"
    }
  },
  {
    "user_id": "demo-user-2",
    "player_id": "46442",
    "player_name": "Maverick McNealy",
    "status": "confirmed",
    "profiles": {
      "display_name": "Diane Cho"
    },
    "tiers": {
      "tier_number": 5,
      "label": "Tier 5"
    }
  },
  {
    "user_id": "demo-user-2",
    "player_id": "33204",
    "player_name": "Shane Lowry",
    "status": "confirmed",
    "profiles": {
      "display_name": "Diane Cho"
    },
    "tiers": {
      "tier_number": 6,
      "label": "Tier 6"
    }
  },
  {
    "user_id": "demo-user-2",
    "player_id": "25493",
    "player_name": "Nick Taylor",
    "status": "confirmed",
    "profiles": {
      "display_name": "Diane Cho"
    },
    "tiers": {
      "tier_number": 7,
      "label": "Wildcard 1"
    }
  },
  {
    "user_id": "demo-user-2",
    "player_id": "51600",
    "player_name": "Jimmy Stanger",
    "status": "confirmed",
    "profiles": {
      "display_name": "Diane Cho"
    },
    "tiers": {
      "tier_number": 8,
      "label": "Wildcard 2"
    }
  },
  {
    "user_id": "demo-user-3",
    "player_id": "48081",
    "player_name": "Xander Schauffele",
    "status": "confirmed",
    "profiles": {
      "display_name": "Tyler Reyes"
    },
    "tiers": {
      "tier_number": 1,
      "label": "Tier 1"
    }
  },
  {
    "user_id": "demo-user-3",
    "player_id": "52955",
    "player_name": "Ludvig Åberg",
    "status": "confirmed",
    "profiles": {
      "display_name": "Tyler Reyes"
    },
    "tiers": {
      "tier_number": 2,
      "label": "Tier 2"
    }
  },
  {
    "user_id": "demo-user-3",
    "player_id": "36689",
    "player_name": "Brooks Koepka",
    "status": "confirmed",
    "profiles": {
      "display_name": "Tyler Reyes"
    },
    "tiers": {
      "tier_number": 3,
      "label": "Tier 3"
    }
  },
  {
    "user_id": "demo-user-3",
    "player_id": "33448",
    "player_name": "Justin Thomas",
    "status": "confirmed",
    "profiles": {
      "display_name": "Tyler Reyes"
    },
    "tiers": {
      "tier_number": 4,
      "label": "Tier 4"
    }
  },
  {
    "user_id": "demo-user-3",
    "player_id": "48117",
    "player_name": "Kurt Kitayama",
    "status": "confirmed",
    "profiles": {
      "display_name": "Tyler Reyes"
    },
    "tiers": {
      "tier_number": 5,
      "label": "Tier 5"
    }
  },
  {
    "user_id": "demo-user-3",
    "player_id": "52215",
    "player_name": "Robert MacIntyre",
    "status": "confirmed",
    "profiles": {
      "display_name": "Tyler Reyes"
    },
    "tiers": {
      "tier_number": 6,
      "label": "Tier 6"
    }
  },
  {
    "user_id": "demo-user-3",
    "player_id": "39997",
    "player_name": "Corey Conners",
    "status": "confirmed",
    "profiles": {
      "display_name": "Tyler Reyes"
    },
    "tiers": {
      "tier_number": 7,
      "label": "Wildcard 1"
    }
  },
  {
    "user_id": "demo-user-3",
    "player_id": "58168",
    "player_name": "Davis Thompson",
    "status": "confirmed",
    "profiles": {
      "display_name": "Tyler Reyes"
    },
    "tiers": {
      "tier_number": 8,
      "label": "Wildcard 2"
    }
  },
  {
    "user_id": "demo-user-4",
    "player_id": "46970",
    "player_name": "Jon Rahm",
    "status": "confirmed",
    "profiles": {
      "display_name": "Priya Nair"
    },
    "tiers": {
      "tier_number": 1,
      "label": "Tier 1"
    }
  },
  {
    "user_id": "demo-user-4",
    "player_id": "40098",
    "player_name": "Matt Fitzpatrick",
    "status": "confirmed",
    "profiles": {
      "display_name": "Priya Nair"
    },
    "tiers": {
      "tier_number": 2,
      "label": "Tier 2"
    }
  },
  {
    "user_id": "demo-user-4",
    "player_id": "36689",
    "player_name": "Brooks Koepka",
    "status": "confirmed",
    "profiles": {
      "display_name": "Priya Nair"
    },
    "tiers": {
      "tier_number": 3,
      "label": "Tier 3"
    }
  },
  {
    "user_id": "demo-user-4",
    "player_id": "33448",
    "player_name": "Justin Thomas",
    "status": "confirmed",
    "profiles": {
      "display_name": "Priya Nair"
    },
    "tiers": {
      "tier_number": 4,
      "label": "Tier 4"
    }
  },
  {
    "user_id": "demo-user-4",
    "player_id": "27349",
    "player_name": "Alex Noren",
    "status": "confirmed",
    "profiles": {
      "display_name": "Priya Nair"
    },
    "tiers": {
      "tier_number": 5,
      "label": "Tier 5"
    }
  },
  {
    "user_id": "demo-user-4",
    "player_id": "52215",
    "player_name": "Robert MacIntyre",
    "status": "confirmed",
    "profiles": {
      "display_name": "Priya Nair"
    },
    "tiers": {
      "tier_number": 6,
      "label": "Tier 6"
    }
  },
  {
    "user_id": "demo-user-4",
    "player_id": "57975",
    "player_name": "Harry Hall",
    "status": "confirmed",
    "profiles": {
      "display_name": "Priya Nair"
    },
    "tiers": {
      "tier_number": 7,
      "label": "Wildcard 1"
    }
  },
  {
    "user_id": "demo-user-4",
    "player_id": "51950",
    "player_name": "Max McGreevy",
    "status": "confirmed",
    "profiles": {
      "display_name": "Priya Nair"
    },
    "tiers": {
      "tier_number": 8,
      "label": "Wildcard 2"
    }
  },
  {
    "user_id": "demo-user-5",
    "player_id": "28237",
    "player_name": "Rory McIlroy",
    "status": "confirmed",
    "profiles": {
      "display_name": "Sam Whitfield"
    },
    "tiers": {
      "tier_number": 1,
      "label": "Tier 1"
    }
  },
  {
    "user_id": "demo-user-5",
    "player_id": "37455",
    "player_name": "Si Woo Kim",
    "status": "confirmed",
    "profiles": {
      "display_name": "Sam Whitfield"
    },
    "tiers": {
      "tier_number": 2,
      "label": "Tier 2"
    }
  },
  {
    "user_id": "demo-user-5",
    "player_id": "36689",
    "player_name": "Brooks Koepka",
    "status": "confirmed",
    "profiles": {
      "display_name": "Sam Whitfield"
    },
    "tiers": {
      "tier_number": 3,
      "label": "Tier 3"
    }
  },
  {
    "user_id": "demo-user-5",
    "player_id": "22405",
    "player_name": "Justin Rose",
    "status": "confirmed",
    "profiles": {
      "display_name": "Sam Whitfield"
    },
    "tiers": {
      "tier_number": 4,
      "label": "Tier 4"
    }
  },
  {
    "user_id": "demo-user-5",
    "player_id": "48117",
    "player_name": "Kurt Kitayama",
    "status": "confirmed",
    "profiles": {
      "display_name": "Sam Whitfield"
    },
    "tiers": {
      "tier_number": 5,
      "label": "Tier 5"
    }
  },
  {
    "user_id": "demo-user-5",
    "player_id": "52215",
    "player_name": "Robert MacIntyre",
    "status": "confirmed",
    "profiles": {
      "display_name": "Sam Whitfield"
    },
    "tiers": {
      "tier_number": 6,
      "label": "Tier 6"
    }
  },
  {
    "user_id": "demo-user-5",
    "player_id": "49960",
    "player_name": "Sepp Straka",
    "status": "confirmed",
    "profiles": {
      "display_name": "Sam Whitfield"
    },
    "tiers": {
      "tier_number": 7,
      "label": "Wildcard 1"
    }
  },
  {
    "user_id": "demo-user-5",
    "player_id": "51600",
    "player_name": "Jimmy Stanger",
    "status": "confirmed",
    "profiles": {
      "display_name": "Sam Whitfield"
    },
    "tiers": {
      "tier_number": 8,
      "label": "Wildcard 2"
    }
  },
  {
    "user_id": "demo-user-6",
    "player_id": "46046",
    "player_name": "Scottie Scheffler",
    "status": "confirmed",
    "profiles": {
      "display_name": "Jordan Lake"
    },
    "tiers": {
      "tier_number": 1,
      "label": "Tier 1"
    }
  },
  {
    "user_id": "demo-user-6",
    "player_id": "37455",
    "player_name": "Si Woo Kim",
    "status": "confirmed",
    "profiles": {
      "display_name": "Jordan Lake"
    },
    "tiers": {
      "tier_number": 2,
      "label": "Tier 2"
    }
  },
  {
    "user_id": "demo-user-6",
    "player_id": "52453",
    "player_name": "Nicolai Højgaard",
    "status": "confirmed",
    "profiles": {
      "display_name": "Jordan Lake"
    },
    "tiers": {
      "tier_number": 3,
      "label": "Tier 3"
    }
  },
  {
    "user_id": "demo-user-6",
    "player_id": "22405",
    "player_name": "Justin Rose",
    "status": "confirmed",
    "profiles": {
      "display_name": "Jordan Lake"
    },
    "tiers": {
      "tier_number": 4,
      "label": "Tier 4"
    }
  },
  {
    "user_id": "demo-user-6",
    "player_id": "45486",
    "player_name": "Joaquin Niemann",
    "status": "confirmed",
    "profiles": {
      "display_name": "Jordan Lake"
    },
    "tiers": {
      "tier_number": 5,
      "label": "Tier 5"
    }
  },
  {
    "user_id": "demo-user-6",
    "player_id": "52215",
    "player_name": "Robert MacIntyre",
    "status": "confirmed",
    "profiles": {
      "display_name": "Jordan Lake"
    },
    "tiers": {
      "tier_number": 6,
      "label": "Tier 6"
    }
  },
  {
    "user_id": "demo-user-6",
    "player_id": "32102",
    "player_name": "Rickie Fowler",
    "status": "confirmed",
    "profiles": {
      "display_name": "Jordan Lake"
    },
    "tiers": {
      "tier_number": 7,
      "label": "Wildcard 1"
    }
  },
  {
    "user_id": "demo-user-6",
    "player_id": "34371",
    "player_name": "Adrien Saddier",
    "status": "confirmed",
    "profiles": {
      "display_name": "Jordan Lake"
    },
    "tiers": {
      "tier_number": 8,
      "label": "Wildcard 2"
    }
  },
  {
    "user_id": "demo-user-7",
    "player_id": "46970",
    "player_name": "Jon Rahm",
    "status": "confirmed",
    "profiles": {
      "display_name": "Nina Alvarez"
    },
    "tiers": {
      "tier_number": 1,
      "label": "Tier 1"
    }
  },
  {
    "user_id": "demo-user-7",
    "player_id": "37455",
    "player_name": "Si Woo Kim",
    "status": "confirmed",
    "profiles": {
      "display_name": "Nina Alvarez"
    },
    "tiers": {
      "tier_number": 2,
      "label": "Tier 2"
    }
  },
  {
    "user_id": "demo-user-7",
    "player_id": "52453",
    "player_name": "Nicolai Højgaard",
    "status": "confirmed",
    "profiles": {
      "display_name": "Nina Alvarez"
    },
    "tiers": {
      "tier_number": 3,
      "label": "Tier 3"
    }
  },
  {
    "user_id": "demo-user-7",
    "player_id": "39324",
    "player_name": "J.J. Spaun",
    "status": "confirmed",
    "profiles": {
      "display_name": "Nina Alvarez"
    },
    "tiers": {
      "tier_number": 4,
      "label": "Tier 4"
    }
  },
  {
    "user_id": "demo-user-7",
    "player_id": "54591",
    "player_name": "Ben Griffin",
    "status": "confirmed",
    "profiles": {
      "display_name": "Nina Alvarez"
    },
    "tiers": {
      "tier_number": 5,
      "label": "Tier 5"
    }
  },
  {
    "user_id": "demo-user-7",
    "player_id": "33204",
    "player_name": "Shane Lowry",
    "status": "confirmed",
    "profiles": {
      "display_name": "Nina Alvarez"
    },
    "tiers": {
      "tier_number": 6,
      "label": "Tier 6"
    }
  },
  {
    "user_id": "demo-user-7",
    "player_id": "40026",
    "player_name": "Daniel Berger",
    "status": "confirmed",
    "profiles": {
      "display_name": "Nina Alvarez"
    },
    "tiers": {
      "tier_number": 7,
      "label": "Wildcard 1"
    }
  },
  {
    "user_id": "demo-user-7",
    "player_id": "55893",
    "player_name": "Sam Stevens",
    "status": "confirmed",
    "profiles": {
      "display_name": "Nina Alvarez"
    },
    "tiers": {
      "tier_number": 8,
      "label": "Wildcard 2"
    }
  },
  {
    "user_id": "demo-user-8",
    "player_id": "57366",
    "player_name": "Cameron Young",
    "status": "confirmed",
    "profiles": {
      "display_name": "Greg Holloway"
    },
    "tiers": {
      "tier_number": 1,
      "label": "Tier 1"
    }
  },
  {
    "user_id": "demo-user-8",
    "player_id": "34363",
    "player_name": "Tyrrell Hatton",
    "status": "confirmed",
    "profiles": {
      "display_name": "Greg Holloway"
    },
    "tiers": {
      "tier_number": 2,
      "label": "Tier 2"
    }
  },
  {
    "user_id": "demo-user-8",
    "player_id": "52453",
    "player_name": "Nicolai Højgaard",
    "status": "confirmed",
    "profiles": {
      "display_name": "Greg Holloway"
    },
    "tiers": {
      "tier_number": 3,
      "label": "Tier 3"
    }
  },
  {
    "user_id": "demo-user-8",
    "player_id": "39324",
    "player_name": "J.J. Spaun",
    "status": "confirmed",
    "profiles": {
      "display_name": "Greg Holloway"
    },
    "tiers": {
      "tier_number": 4,
      "label": "Tier 4"
    }
  },
  {
    "user_id": "demo-user-8",
    "player_id": "48117",
    "player_name": "Kurt Kitayama",
    "status": "confirmed",
    "profiles": {
      "display_name": "Greg Holloway"
    },
    "tiers": {
      "tier_number": 5,
      "label": "Tier 5"
    }
  },
  {
    "user_id": "demo-user-8",
    "player_id": "46414",
    "player_name": "Aaron Rai",
    "status": "confirmed",
    "profiles": {
      "display_name": "Greg Holloway"
    },
    "tiers": {
      "tier_number": 6,
      "label": "Tier 6"
    }
  },
  {
    "user_id": "demo-user-8",
    "player_id": "29936",
    "player_name": "Ryan Fox",
    "status": "confirmed",
    "profiles": {
      "display_name": "Greg Holloway"
    },
    "tiers": {
      "tier_number": 7,
      "label": "Wildcard 1"
    }
  },
  {
    "user_id": "demo-user-8",
    "player_id": "51287",
    "player_name": "Ryo Hisatsune",
    "status": "confirmed",
    "profiles": {
      "display_name": "Greg Holloway"
    },
    "tiers": {
      "tier_number": 8,
      "label": "Wildcard 2"
    }
  },
  {
    "user_id": "demo-user-9",
    "player_id": "46970",
    "player_name": "Jon Rahm",
    "status": "confirmed",
    "profiles": {
      "display_name": "Casey Monroe"
    },
    "tiers": {
      "tier_number": 1,
      "label": "Tier 1"
    }
  },
  {
    "user_id": "demo-user-9",
    "player_id": "47959",
    "player_name": "Bryson DeChambeau",
    "status": "confirmed",
    "profiles": {
      "display_name": "Casey Monroe"
    },
    "tiers": {
      "tier_number": 2,
      "label": "Tier 2"
    }
  },
  {
    "user_id": "demo-user-9",
    "player_id": "47504",
    "player_name": "Sam Burns",
    "status": "confirmed",
    "profiles": {
      "display_name": "Casey Monroe"
    },
    "tiers": {
      "tier_number": 3,
      "label": "Tier 3"
    }
  },
  {
    "user_id": "demo-user-9",
    "player_id": "35450",
    "player_name": "Patrick Cantlay",
    "status": "confirmed",
    "profiles": {
      "display_name": "Casey Monroe"
    },
    "tiers": {
      "tier_number": 4,
      "label": "Tier 4"
    }
  },
  {
    "user_id": "demo-user-9",
    "player_id": "46442",
    "player_name": "Maverick McNealy",
    "status": "confirmed",
    "profiles": {
      "display_name": "Casey Monroe"
    },
    "tiers": {
      "tier_number": 5,
      "label": "Tier 5"
    }
  },
  {
    "user_id": "demo-user-9",
    "player_id": "37378",
    "player_name": "Min Woo Lee",
    "status": "confirmed",
    "profiles": {
      "display_name": "Casey Monroe"
    },
    "tiers": {
      "tier_number": 6,
      "label": "Tier 6"
    }
  },
  {
    "user_id": "demo-user-9",
    "player_id": "39971",
    "player_name": "Sungjae Im",
    "status": "confirmed",
    "profiles": {
      "display_name": "Casey Monroe"
    },
    "tiers": {
      "tier_number": 7,
      "label": "Wildcard 1"
    }
  },
  {
    "user_id": "demo-user-9",
    "player_id": "39975",
    "player_name": "Michael Kim",
    "status": "confirmed",
    "profiles": {
      "display_name": "Casey Monroe"
    },
    "tiers": {
      "tier_number": 8,
      "label": "Wildcard 2"
    }
  },
  {
    "user_id": "demo-user-10",
    "player_id": "46970",
    "player_name": "Jon Rahm",
    "status": "confirmed",
    "profiles": {
      "display_name": "Erin Park"
    },
    "tiers": {
      "tier_number": 1,
      "label": "Tier 1"
    }
  },
  {
    "user_id": "demo-user-10",
    "player_id": "37455",
    "player_name": "Si Woo Kim",
    "status": "confirmed",
    "profiles": {
      "display_name": "Erin Park"
    },
    "tiers": {
      "tier_number": 2,
      "label": "Tier 2"
    }
  },
  {
    "user_id": "demo-user-10",
    "player_id": "34360",
    "player_name": "Patrick Reed",
    "status": "confirmed",
    "profiles": {
      "display_name": "Erin Park"
    },
    "tiers": {
      "tier_number": 3,
      "label": "Tier 3"
    }
  },
  {
    "user_id": "demo-user-10",
    "player_id": "39324",
    "player_name": "J.J. Spaun",
    "status": "confirmed",
    "profiles": {
      "display_name": "Erin Park"
    },
    "tiers": {
      "tier_number": 4,
      "label": "Tier 4"
    }
  },
  {
    "user_id": "demo-user-10",
    "player_id": "54591",
    "player_name": "Ben Griffin",
    "status": "confirmed",
    "profiles": {
      "display_name": "Erin Park"
    },
    "tiers": {
      "tier_number": 5,
      "label": "Tier 5"
    }
  },
  {
    "user_id": "demo-user-10",
    "player_id": "46414",
    "player_name": "Aaron Rai",
    "status": "confirmed",
    "profiles": {
      "display_name": "Erin Park"
    },
    "tiers": {
      "tier_number": 6,
      "label": "Tier 6"
    }
  },
  {
    "user_id": "demo-user-10",
    "player_id": "27644",
    "player_name": "Brian Harman",
    "status": "confirmed",
    "profiles": {
      "display_name": "Erin Park"
    },
    "tiers": {
      "tier_number": 7,
      "label": "Wildcard 1"
    }
  },
  {
    "user_id": "demo-user-10",
    "player_id": "55182",
    "player_name": "Tom Kim",
    "status": "confirmed",
    "profiles": {
      "display_name": "Erin Park"
    },
    "tiers": {
      "tier_number": 8,
      "label": "Wildcard 2"
    }
  },
  {
    "user_id": "demo-user-11",
    "player_id": "46970",
    "player_name": "Jon Rahm",
    "status": "confirmed",
    "profiles": {
      "display_name": "Devon Pierce"
    },
    "tiers": {
      "tier_number": 1,
      "label": "Tier 1"
    }
  },
  {
    "user_id": "demo-user-11",
    "player_id": "34363",
    "player_name": "Tyrrell Hatton",
    "status": "confirmed",
    "profiles": {
      "display_name": "Devon Pierce"
    },
    "tiers": {
      "tier_number": 2,
      "label": "Tier 2"
    }
  },
  {
    "user_id": "demo-user-11",
    "player_id": "47504",
    "player_name": "Sam Burns",
    "status": "confirmed",
    "profiles": {
      "display_name": "Devon Pierce"
    },
    "tiers": {
      "tier_number": 3,
      "label": "Tier 3"
    }
  },
  {
    "user_id": "demo-user-11",
    "player_id": "51766",
    "player_name": "Wyndham Clark",
    "status": "confirmed",
    "profiles": {
      "display_name": "Devon Pierce"
    },
    "tiers": {
      "tier_number": 4,
      "label": "Tier 4"
    }
  },
  {
    "user_id": "demo-user-11",
    "player_id": "45486",
    "player_name": "Joaquin Niemann",
    "status": "confirmed",
    "profiles": {
      "display_name": "Devon Pierce"
    },
    "tiers": {
      "tier_number": 5,
      "label": "Tier 5"
    }
  },
  {
    "user_id": "demo-user-11",
    "player_id": "33204",
    "player_name": "Shane Lowry",
    "status": "confirmed",
    "profiles": {
      "display_name": "Devon Pierce"
    },
    "tiers": {
      "tier_number": 6,
      "label": "Tier 6"
    }
  },
  {
    "user_id": "demo-user-11",
    "player_id": "57975",
    "player_name": "Harry Hall",
    "status": "confirmed",
    "profiles": {
      "display_name": "Devon Pierce"
    },
    "tiers": {
      "tier_number": 7,
      "label": "Wildcard 1"
    }
  },
  {
    "user_id": "demo-user-11",
    "player_id": "64054",
    "player_name": "Caleb Surratt",
    "status": "confirmed",
    "profiles": {
      "display_name": "Devon Pierce"
    },
    "tiers": {
      "tier_number": 8,
      "label": "Wildcard 2"
    }
  },
  {
    "user_id": "demo-user-12",
    "player_id": "28237",
    "player_name": "Rory McIlroy",
    "status": "confirmed",
    "profiles": {
      "display_name": "Hannah Wills"
    },
    "tiers": {
      "tier_number": 1,
      "label": "Tier 1"
    }
  },
  {
    "user_id": "demo-user-12",
    "player_id": "40098",
    "player_name": "Matt Fitzpatrick",
    "status": "confirmed",
    "profiles": {
      "display_name": "Hannah Wills"
    },
    "tiers": {
      "tier_number": 2,
      "label": "Tier 2"
    }
  },
  {
    "user_id": "demo-user-12",
    "player_id": "50525",
    "player_name": "Collin Morikawa",
    "status": "confirmed",
    "profiles": {
      "display_name": "Hannah Wills"
    },
    "tiers": {
      "tier_number": 3,
      "label": "Tier 3"
    }
  },
  {
    "user_id": "demo-user-12",
    "player_id": "46717",
    "player_name": "Viktor Hovland",
    "status": "confirmed",
    "profiles": {
      "display_name": "Hannah Wills"
    },
    "tiers": {
      "tier_number": 4,
      "label": "Tier 4"
    }
  },
  {
    "user_id": "demo-user-12",
    "player_id": "48117",
    "player_name": "Kurt Kitayama",
    "status": "confirmed",
    "profiles": {
      "display_name": "Hannah Wills"
    },
    "tiers": {
      "tier_number": 5,
      "label": "Tier 5"
    }
  },
  {
    "user_id": "demo-user-12",
    "player_id": "34046",
    "player_name": "Jordan Spieth",
    "status": "confirmed",
    "profiles": {
      "display_name": "Hannah Wills"
    },
    "tiers": {
      "tier_number": 6,
      "label": "Tier 6"
    }
  },
  {
    "user_id": "demo-user-12",
    "player_id": "29936",
    "player_name": "Ryan Fox",
    "status": "confirmed",
    "profiles": {
      "display_name": "Hannah Wills"
    },
    "tiers": {
      "tier_number": 7,
      "label": "Wildcard 1"
    }
  },
  {
    "user_id": "demo-user-12",
    "player_id": "64054",
    "player_name": "Caleb Surratt",
    "status": "confirmed",
    "profiles": {
      "display_name": "Hannah Wills"
    },
    "tiers": {
      "tier_number": 8,
      "label": "Wildcard 2"
    }
  }
];
export const leaderboardData = {
  "roundId": 3,
  "status": "In Progress",
  "leaderboardRows": [
    {
      "playerId": "51766",
      "firstName": "Wyndham",
      "lastName": "Clark",
      "total": "-7",
      "thru": "F",
      "position": "1",
      "status": "complete"
    },
    {
      "playerId": "46046",
      "firstName": "Scottie",
      "lastName": "Scheffler",
      "total": "-1",
      "thru": "F",
      "position": "T2",
      "status": "complete"
    },
    {
      "playerId": "51634",
      "firstName": "Sahith",
      "lastName": "Theegala",
      "total": "-1",
      "thru": "F",
      "position": "T2",
      "status": "complete"
    },
    {
      "playerId": "55182",
      "firstName": "Tom",
      "lastName": "Kim",
      "total": "-1",
      "thru": "F",
      "position": "T2",
      "status": "complete"
    },
    {
      "playerId": "55893",
      "firstName": "Sam",
      "lastName": "Stevens",
      "total": "-1",
      "thru": "F",
      "position": "T2",
      "status": "complete"
    },
    {
      "playerId": "31646",
      "firstName": "Emiliano",
      "lastName": "Grillo",
      "total": "E",
      "thru": "F",
      "position": "T6",
      "status": "complete"
    },
    {
      "playerId": "39546",
      "firstName": "Keith",
      "lastName": "Mitchell",
      "total": "E",
      "thru": "F",
      "position": "T6",
      "status": "complete"
    },
    {
      "playerId": "47504",
      "firstName": "Sam",
      "lastName": "Burns",
      "total": "E",
      "thru": "F",
      "position": "T6",
      "status": "complete"
    },
    {
      "playerId": "48081",
      "firstName": "Xander",
      "lastName": "Schauffele",
      "total": "E",
      "thru": "F",
      "position": "T6",
      "status": "complete"
    },
    {
      "playerId": "30911",
      "firstName": "Tommy",
      "lastName": "Fleetwood",
      "total": "+1",
      "thru": "F",
      "position": "T10",
      "status": "complete"
    },
    {
      "playerId": "50525",
      "firstName": "Collin",
      "lastName": "Morikawa",
      "total": "+1",
      "thru": "F",
      "position": "T10",
      "status": "complete"
    },
    {
      "playerId": "40098",
      "firstName": "Matt",
      "lastName": "Fitzpatrick",
      "total": "+1",
      "thru": "F",
      "position": "T10",
      "status": "complete"
    },
    {
      "playerId": "33141",
      "firstName": "Keegan",
      "lastName": "Bradley",
      "total": "+2",
      "thru": "F",
      "position": "T13",
      "status": "complete"
    },
    {
      "playerId": "39997",
      "firstName": "Corey",
      "lastName": "Conners",
      "total": "+2",
      "thru": "F",
      "position": "T13",
      "status": "complete"
    },
    {
      "playerId": "39975",
      "firstName": "Michael",
      "lastName": "Kim",
      "total": "+3",
      "thru": "F",
      "position": "T17",
      "status": "complete"
    },
    {
      "playerId": "39971",
      "firstName": "Sungjae",
      "lastName": "Im",
      "total": "+3",
      "thru": "F",
      "position": "T17",
      "status": "complete"
    },
    {
      "playerId": "46414",
      "firstName": "Aaron",
      "lastName": "Rai",
      "total": "+3",
      "thru": "F",
      "position": "T17",
      "status": "complete"
    },
    {
      "playerId": "27644",
      "firstName": "Brian",
      "lastName": "Harman",
      "total": "+3",
      "thru": "F",
      "position": "T17",
      "status": "complete"
    },
    {
      "playerId": "46442",
      "firstName": "Maverick",
      "lastName": "McNealy",
      "total": "+3",
      "thru": "F",
      "position": "T17",
      "status": "complete"
    },
    {
      "playerId": "28237",
      "firstName": "Rory",
      "lastName": "McIlroy",
      "total": "+3",
      "thru": "F",
      "position": "T17",
      "status": "complete"
    },
    {
      "playerId": "51287",
      "firstName": "Ryo",
      "lastName": "Hisatsune",
      "total": "+3",
      "thru": "F",
      "position": "T17",
      "status": "complete"
    },
    {
      "playerId": "34363",
      "firstName": "Tyrrell",
      "lastName": "Hatton",
      "total": "+4",
      "thru": "F",
      "position": "T29",
      "status": "complete"
    },
    {
      "playerId": "54591",
      "firstName": "Ben",
      "lastName": "Griffin",
      "total": "+4",
      "thru": "F",
      "position": "T29",
      "status": "complete"
    },
    {
      "playerId": "22405",
      "firstName": "Justin",
      "lastName": "Rose",
      "total": "+4",
      "thru": "F",
      "position": "T29",
      "status": "complete"
    },
    {
      "playerId": "51950",
      "firstName": "Max",
      "lastName": "McGreevy",
      "total": "+4",
      "thru": "F",
      "position": "T29",
      "status": "complete"
    },
    {
      "playerId": "33448",
      "firstName": "Justin",
      "lastName": "Thomas",
      "total": "+4",
      "thru": "F",
      "position": "T29",
      "status": "complete"
    },
    {
      "playerId": "45486",
      "firstName": "Joaquin",
      "lastName": "Niemann",
      "total": "+5",
      "thru": "F",
      "position": "T38",
      "status": "complete"
    },
    {
      "playerId": "57366",
      "firstName": "Cameron",
      "lastName": "Young",
      "total": "+5",
      "thru": "F",
      "position": "T38",
      "status": "complete"
    },
    {
      "playerId": "34046",
      "firstName": "Jordan",
      "lastName": "Spieth",
      "total": "+6",
      "thru": "F",
      "position": "T42",
      "status": "complete"
    },
    {
      "playerId": "52215",
      "firstName": "Robert",
      "lastName": "MacIntyre",
      "total": "+7",
      "thru": "F",
      "position": "T47",
      "status": "complete"
    },
    {
      "playerId": "29936",
      "firstName": "Ryan",
      "lastName": "Fox",
      "total": "+7",
      "thru": "F",
      "position": "T47",
      "status": "complete"
    },
    {
      "playerId": "52955",
      "firstName": "Ludvig",
      "lastName": "Åberg",
      "total": "+7",
      "thru": "F",
      "position": "T47",
      "status": "complete"
    },
    {
      "playerId": "48117",
      "firstName": "Kurt",
      "lastName": "Kitayama",
      "total": "+8",
      "thru": "F",
      "position": "T55",
      "status": "complete"
    },
    {
      "playerId": "64054",
      "firstName": "Caleb",
      "lastName": "Surratt",
      "total": "+9",
      "thru": "F",
      "position": "T62",
      "status": "complete"
    },
    {
      "playerId": "32839",
      "firstName": "Hideki",
      "lastName": "Matsuyama",
      "total": "+11",
      "thru": "F",
      "position": "T65",
      "status": "complete"
    },
    {
      "playerId": "29484",
      "firstName": "Peter",
      "lastName": "Uihlein",
      "total": "+14",
      "thru": "F",
      "position": "70",
      "status": "complete"
    },
    {
      "playerId": "47959",
      "firstName": "Bryson",
      "lastName": "DeChambeau",
      "total": "+5",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "46717",
      "firstName": "Viktor",
      "lastName": "Hovland",
      "total": "+5",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "32102",
      "firstName": "Rickie",
      "lastName": "Fowler",
      "total": "+5",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "34360",
      "firstName": "Patrick",
      "lastName": "Reed",
      "total": "+5",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "34099",
      "firstName": "Harris",
      "lastName": "English",
      "total": "+5",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "25493",
      "firstName": "Nick",
      "lastName": "Taylor",
      "total": "+5",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "33204",
      "firstName": "Shane",
      "lastName": "Lowry",
      "total": "+6",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "46970",
      "firstName": "Jon",
      "lastName": "Rahm",
      "total": "+6",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "35450",
      "firstName": "Patrick",
      "lastName": "Cantlay",
      "total": "+6",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "37455",
      "firstName": "Si Woo",
      "lastName": "Kim",
      "total": "+6",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "27349",
      "firstName": "Alex",
      "lastName": "Noren",
      "total": "+6",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "34371",
      "firstName": "Adrien",
      "lastName": "Saddier",
      "total": "+7",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "37378",
      "firstName": "Min Woo",
      "lastName": "Lee",
      "total": "+7",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "51600",
      "firstName": "Jimmy",
      "lastName": "Stanger",
      "total": "+7",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "49960",
      "firstName": "Sepp",
      "lastName": "Straka",
      "total": "+7",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "39324",
      "firstName": "J.J.",
      "lastName": "Spaun",
      "total": "+8",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "52453",
      "firstName": "Nicolai",
      "lastName": "Højgaard",
      "total": "+9",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "58168",
      "firstName": "Davis",
      "lastName": "Thompson",
      "total": "+10",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "36689",
      "firstName": "Brooks",
      "lastName": "Koepka",
      "total": "+10",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "40026",
      "firstName": "Daniel",
      "lastName": "Berger",
      "total": "+10",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    },
    {
      "playerId": "57975",
      "firstName": "Harry",
      "lastName": "Hall",
      "total": "+11",
      "thru": "",
      "position": "CUT",
      "status": "cut"
    }
  ]
};
export const standings = [
  {
    "user_id": "demo-user-11",
    "display_name": "Devon Pierce",
    "total_score": 11,
    "picks": [
      {
        "player_name": "Wyndham Clark",
        "player_id": "51766",
        "score": -7,
        "rawScore": "-7",
        "thru": "F",
        "position": "1",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Sam Burns",
        "player_id": "47504",
        "score": 0,
        "rawScore": "E",
        "thru": "F",
        "position": "T6",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Tyrrell Hatton",
        "player_id": "34363",
        "score": 4,
        "rawScore": "+4",
        "thru": "F",
        "position": "T29",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Joaquin Niemann",
        "player_id": "45486",
        "score": 5,
        "rawScore": "+5",
        "thru": "F",
        "position": "T38",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Caleb Surratt",
        "player_id": "64054",
        "score": 9,
        "rawScore": "+9",
        "thru": "F",
        "position": "T62",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Jon Rahm",
        "player_id": "46970",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Shane Lowry",
        "player_id": "33204",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Harry Hall",
        "player_id": "57975",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      }
    ],
    "rank": 1
  },
  {
    "user_id": "demo-user-1",
    "display_name": "Marcus Bennett",
    "total_score": 13,
    "picks": [
      {
        "player_name": "Xander Schauffele",
        "player_id": "48081",
        "score": 0,
        "rawScore": "E",
        "thru": "F",
        "position": "T6",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Sam Burns",
        "player_id": "47504",
        "score": 0,
        "rawScore": "E",
        "thru": "F",
        "position": "T6",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Keegan Bradley",
        "player_id": "33141",
        "score": 2,
        "rawScore": "+2",
        "thru": "F",
        "position": "T13",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Justin Thomas",
        "player_id": "33448",
        "score": 4,
        "rawScore": "+4",
        "thru": "F",
        "position": "T29",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Ludvig Åberg",
        "player_id": "52955",
        "score": 7,
        "rawScore": "+7",
        "thru": "F",
        "position": "T47",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Hideki Matsuyama",
        "player_id": "32839",
        "score": 11,
        "rawScore": "+11",
        "thru": "F",
        "position": "T65",
        "withdrawn": false,
        "cut": false,
        "used_in_total": false
      },
      {
        "player_name": "Peter Uihlein",
        "player_id": "29484",
        "score": 14,
        "rawScore": "+14",
        "thru": "F",
        "position": "70",
        "withdrawn": false,
        "cut": false,
        "used_in_total": false
      },
      {
        "player_name": "Harris English",
        "player_id": "34099",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      }
    ],
    "rank": 2
  },
  {
    "user_id": "demo-user-12",
    "display_name": "Hannah Wills",
    "total_score": 18,
    "picks": [
      {
        "player_name": "Matt Fitzpatrick",
        "player_id": "40098",
        "score": 1,
        "rawScore": "+1",
        "thru": "F",
        "position": "T10",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Collin Morikawa",
        "player_id": "50525",
        "score": 1,
        "rawScore": "+1",
        "thru": "F",
        "position": "T10",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Rory McIlroy",
        "player_id": "28237",
        "score": 3,
        "rawScore": "+3",
        "thru": "F",
        "position": "T17",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Jordan Spieth",
        "player_id": "34046",
        "score": 6,
        "rawScore": "+6",
        "thru": "F",
        "position": "T42",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Ryan Fox",
        "player_id": "29936",
        "score": 7,
        "rawScore": "+7",
        "thru": "F",
        "position": "T47",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Kurt Kitayama",
        "player_id": "48117",
        "score": 8,
        "rawScore": "+8",
        "thru": "F",
        "position": "T55",
        "withdrawn": false,
        "cut": false,
        "used_in_total": false
      },
      {
        "player_name": "Caleb Surratt",
        "player_id": "64054",
        "score": 9,
        "rawScore": "+9",
        "thru": "F",
        "position": "T62",
        "withdrawn": false,
        "cut": false,
        "used_in_total": false
      },
      {
        "player_name": "Viktor Hovland",
        "player_id": "46717",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      }
    ],
    "rank": 3
  },
  {
    "user_id": "demo-user-3",
    "display_name": "Tyler Reyes",
    "total_score": 20,
    "picks": [
      {
        "player_name": "Xander Schauffele",
        "player_id": "48081",
        "score": 0,
        "rawScore": "E",
        "thru": "F",
        "position": "T6",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Corey Conners",
        "player_id": "39997",
        "score": 2,
        "rawScore": "+2",
        "thru": "F",
        "position": "T13",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Justin Thomas",
        "player_id": "33448",
        "score": 4,
        "rawScore": "+4",
        "thru": "F",
        "position": "T29",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Ludvig Åberg",
        "player_id": "52955",
        "score": 7,
        "rawScore": "+7",
        "thru": "F",
        "position": "T47",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Robert MacIntyre",
        "player_id": "52215",
        "score": 7,
        "rawScore": "+7",
        "thru": "F",
        "position": "T47",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Kurt Kitayama",
        "player_id": "48117",
        "score": 8,
        "rawScore": "+8",
        "thru": "F",
        "position": "T55",
        "withdrawn": false,
        "cut": false,
        "used_in_total": false
      },
      {
        "player_name": "Brooks Koepka",
        "player_id": "36689",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Davis Thompson",
        "player_id": "58168",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      }
    ],
    "rank": 4
  },
  {
    "user_id": "demo-user-8",
    "display_name": "Greg Holloway",
    "total_score": 22,
    "picks": [
      {
        "player_name": "Aaron Rai",
        "player_id": "46414",
        "score": 3,
        "rawScore": "+3",
        "thru": "F",
        "position": "T17",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Ryo Hisatsune",
        "player_id": "51287",
        "score": 3,
        "rawScore": "+3",
        "thru": "F",
        "position": "T17",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Tyrrell Hatton",
        "player_id": "34363",
        "score": 4,
        "rawScore": "+4",
        "thru": "F",
        "position": "T29",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Cameron Young",
        "player_id": "57366",
        "score": 5,
        "rawScore": "+5",
        "thru": "F",
        "position": "T38",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Ryan Fox",
        "player_id": "29936",
        "score": 7,
        "rawScore": "+7",
        "thru": "F",
        "position": "T47",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Kurt Kitayama",
        "player_id": "48117",
        "score": 8,
        "rawScore": "+8",
        "thru": "F",
        "position": "T55",
        "withdrawn": false,
        "cut": false,
        "used_in_total": false
      },
      {
        "player_name": "Nicolai Højgaard",
        "player_id": "52453",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "J.J. Spaun",
        "player_id": "39324",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      }
    ],
    "rank": 5
  },
  {
    "user_id": "demo-user-9",
    "display_name": "Casey Monroe",
    "total_score": 29,
    "picks": [
      {
        "player_name": "Sam Burns",
        "player_id": "47504",
        "score": 0,
        "rawScore": "E",
        "thru": "F",
        "position": "T6",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Maverick McNealy",
        "player_id": "46442",
        "score": 3,
        "rawScore": "+3",
        "thru": "F",
        "position": "T17",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Sungjae Im",
        "player_id": "39971",
        "score": 3,
        "rawScore": "+3",
        "thru": "F",
        "position": "T17",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Michael Kim",
        "player_id": "39975",
        "score": 3,
        "rawScore": "+3",
        "thru": "F",
        "position": "T17",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Jon Rahm",
        "player_id": "46970",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": true
      },
      {
        "player_name": "Bryson DeChambeau",
        "player_id": "47959",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Patrick Cantlay",
        "player_id": "35450",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Min Woo Lee",
        "player_id": "37378",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      }
    ],
    "rank": 6
  },
  {
    "user_id": "demo-user-10",
    "display_name": "Erin Park",
    "total_score": 29,
    "picks": [
      {
        "player_name": "Tom Kim",
        "player_id": "55182",
        "score": -1,
        "rawScore": "-1",
        "thru": "F",
        "position": "T2",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Aaron Rai",
        "player_id": "46414",
        "score": 3,
        "rawScore": "+3",
        "thru": "F",
        "position": "T17",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Brian Harman",
        "player_id": "27644",
        "score": 3,
        "rawScore": "+3",
        "thru": "F",
        "position": "T17",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Ben Griffin",
        "player_id": "54591",
        "score": 4,
        "rawScore": "+4",
        "thru": "F",
        "position": "T29",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Jon Rahm",
        "player_id": "46970",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": true
      },
      {
        "player_name": "Si Woo Kim",
        "player_id": "37455",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Patrick Reed",
        "player_id": "34360",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "J.J. Spaun",
        "player_id": "39324",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      }
    ],
    "rank": 6
  },
  {
    "user_id": "demo-user-6",
    "display_name": "Jordan Lake",
    "total_score": 35,
    "picks": [
      {
        "player_name": "Scottie Scheffler",
        "player_id": "46046",
        "score": -1,
        "rawScore": "-1",
        "thru": "F",
        "position": "T2",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Justin Rose",
        "player_id": "22405",
        "score": 4,
        "rawScore": "+4",
        "thru": "F",
        "position": "T29",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Joaquin Niemann",
        "player_id": "45486",
        "score": 5,
        "rawScore": "+5",
        "thru": "F",
        "position": "T38",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Robert MacIntyre",
        "player_id": "52215",
        "score": 7,
        "rawScore": "+7",
        "thru": "F",
        "position": "T47",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Si Woo Kim",
        "player_id": "37455",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": true
      },
      {
        "player_name": "Nicolai Højgaard",
        "player_id": "52453",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Rickie Fowler",
        "player_id": "32102",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Adrien Saddier",
        "player_id": "34371",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      }
    ],
    "rank": 8
  },
  {
    "user_id": "demo-user-2",
    "display_name": "Diane Cho",
    "total_score": 36,
    "picks": [
      {
        "player_name": "Wyndham Clark",
        "player_id": "51766",
        "score": -7,
        "rawScore": "-7",
        "thru": "F",
        "position": "1",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Xander Schauffele",
        "player_id": "48081",
        "score": 0,
        "rawScore": "E",
        "thru": "F",
        "position": "T6",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Maverick McNealy",
        "player_id": "46442",
        "score": 3,
        "rawScore": "+3",
        "thru": "F",
        "position": "T17",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Si Woo Kim",
        "player_id": "37455",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": true
      },
      {
        "player_name": "Brooks Koepka",
        "player_id": "36689",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": true
      },
      {
        "player_name": "Shane Lowry",
        "player_id": "33204",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Nick Taylor",
        "player_id": "25493",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Jimmy Stanger",
        "player_id": "51600",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      }
    ],
    "rank": 9
  },
  {
    "user_id": "demo-user-4",
    "display_name": "Priya Nair",
    "total_score": 36,
    "picks": [
      {
        "player_name": "Matt Fitzpatrick",
        "player_id": "40098",
        "score": 1,
        "rawScore": "+1",
        "thru": "F",
        "position": "T10",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Justin Thomas",
        "player_id": "33448",
        "score": 4,
        "rawScore": "+4",
        "thru": "F",
        "position": "T29",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Max McGreevy",
        "player_id": "51950",
        "score": 4,
        "rawScore": "+4",
        "thru": "F",
        "position": "T29",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Robert MacIntyre",
        "player_id": "52215",
        "score": 7,
        "rawScore": "+7",
        "thru": "F",
        "position": "T47",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Jon Rahm",
        "player_id": "46970",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": true
      },
      {
        "player_name": "Brooks Koepka",
        "player_id": "36689",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Alex Noren",
        "player_id": "27349",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Harry Hall",
        "player_id": "57975",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      }
    ],
    "rank": 9
  },
  {
    "user_id": "demo-user-5",
    "display_name": "Sam Whitfield",
    "total_score": 42,
    "picks": [
      {
        "player_name": "Rory McIlroy",
        "player_id": "28237",
        "score": 3,
        "rawScore": "+3",
        "thru": "F",
        "position": "T17",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Justin Rose",
        "player_id": "22405",
        "score": 4,
        "rawScore": "+4",
        "thru": "F",
        "position": "T29",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Robert MacIntyre",
        "player_id": "52215",
        "score": 7,
        "rawScore": "+7",
        "thru": "F",
        "position": "T47",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Kurt Kitayama",
        "player_id": "48117",
        "score": 8,
        "rawScore": "+8",
        "thru": "F",
        "position": "T55",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Si Woo Kim",
        "player_id": "37455",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": true
      },
      {
        "player_name": "Brooks Koepka",
        "player_id": "36689",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Sepp Straka",
        "player_id": "49960",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Jimmy Stanger",
        "player_id": "51600",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      }
    ],
    "rank": 11
  },
  {
    "user_id": "demo-user-7",
    "display_name": "Nina Alvarez",
    "total_score": 63,
    "picks": [
      {
        "player_name": "Sam Stevens",
        "player_id": "55893",
        "score": -1,
        "rawScore": "-1",
        "thru": "F",
        "position": "T2",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Ben Griffin",
        "player_id": "54591",
        "score": 4,
        "rawScore": "+4",
        "thru": "F",
        "position": "T29",
        "withdrawn": false,
        "cut": false,
        "used_in_total": true
      },
      {
        "player_name": "Jon Rahm",
        "player_id": "46970",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": true
      },
      {
        "player_name": "Si Woo Kim",
        "player_id": "37455",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": true
      },
      {
        "player_name": "Nicolai Højgaard",
        "player_id": "52453",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": true
      },
      {
        "player_name": "J.J. Spaun",
        "player_id": "39324",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Shane Lowry",
        "player_id": "33204",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      },
      {
        "player_name": "Daniel Berger",
        "player_id": "40026",
        "score": 20,
        "rawScore": "+20",
        "thru": "",
        "position": "CUT",
        "withdrawn": false,
        "cut": true,
        "used_in_total": false
      }
    ],
    "rank": 12
  }
];
export const currentUserId = "demo-user-1";
